spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: dv
    password: dv
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:sqls/schema-dev.sql
      data-locations: classpath:sqls/data.sql