spring:
  profiles:
    active: dev
  mail:
    host: localhost
    port: 1025
    username: visitor
    password: visitor
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000