spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  sql:
    init:
      mode: embedded
      schema-locations: classpath:sqls/schema-prod.sql
      data-locations: classpath:sqls/data.sql